spring.application.name=solo-q-server


# 1. ?? ?? ?? (Server Configuration)
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# 2. ??? ?????? ?? (Oracle DB)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

# DB ?? ??
spring.datasource.username=c##tokyo
spring.datasource.password=1234

# 3. JPA / Hibernate ??
spring.jpa.hibernate.ddl-auto=update

# ??? ???? SQL ?? ???? (????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??? ?? ??
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# 4. JWT ?? ?? (Custom)
# ?? ??? ??? ??? (??? ? ??? - Base64 ???? 32? ?? ??)
jwt.secret=ThisIsMyProjecte4c18cfba276632ea939ea7975dc9917@soloq

# ?? ?? ?? (??? ??) - ?: 1?? (60? * 60? * 1000ms)
jwt.expiration=3600000

# 5. ?? ??? ?? (?? ?? ??? ??)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# 1. ?? ?? ?? (Server Configuration)
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# 2. ??? ?????? ?? (Oracle DB)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

# DB ?? ??
spring.datasource.username=c##tokyo
spring.datasource.password=1234

# 3. JPA / Hibernate ??
spring.jpa.hibernate.ddl-auto=update

# ??? ???? SQL ?? ???? (????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??? ?? ??
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# 4. JWT ?? ?? (Custom)
# ?? ??? ??? ??? (??? ? ??? - Base64 ???? 32? ?? ??)
jwt.secret=ThisIsMyProjecte4c18cfba276632ea939ea7975dc9917@soloq

# ?? ?? ?? (??? ??) - ?: 1?? (60? * 60? * 1000ms)
jwt.expiration=3600000

# 5. ?? ??? ?? (?? ?? ??? ??)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB